### ISSUE TITLE
Should x location of robotic arm right be moved to HookesLawConstants?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/hookes-law#10]
When a robotic arm is created, the right end is always at 3 meters, 

```
    this.roboticArm = new RoboticArm( {
      left: this.equivalentSpring.rightProperty.get(),
      right: 3
    } );
```

Should the value 3 be moved to HooksLawConstants?  This would consolidate and clarify.  Right now, one needs to look into RoboticArm documentation to learn the magnitude of 3.

**Comment by pixelzoom** [comment]
3 is actually a default value for the option - perhaps confusing because it tends to be the same as the actual value.

The actual values are specified in the various system models (SingleSpringSystem, SeriesSystem, ParallelSystem) where they look like this:

``` js
    this.roboticArm = new RoboticArm( {
      left: this.spring.rightProperty.get(),
      right: 3
    } );
```

@jessegreenberg Would it be less confusing if the defaults for left and right options in RoboticArm were set to something else?

**Comment by pixelzoom** [comment]
In fact, it might be better to specify the actual values like this in the various system models:

``` js
   this.roboticArm = new RoboticArm( {
      left: this.spring.rightProperty.get(),
      right: this.spring.rightProperty.get() + this.spring.lengthProperty.get()
    } );
```

Assuming the spring is initially at equilibrium, the distance from equilibrium to either the left wall or the robotic arm's 'right' should be the same.

**Comment by pixelzoom** [comment]
I made a few changes, see the commit immediately above.  Summary:

• In RoboticArm, set the defaults for options.left and options.right to something more generic (0 and 1 respectively)

• In system models, compute the value of options.right for RoboticArm, based on the assumption that the spring(s) are initially at equilibrium.

• Add an assertion that the spring(s) are initially at equilibrium (i.e., displacement === 0).

If that makes things clear, feel free to close this issue.

**Comment by jessegreenberg** [comment]
Looks great, thanks!  I think that computing the value in systems models clarifies a lot.  Closing.
