### ISSUE TITLE
Turn off right alignment of icons in panels.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#100]
For https://github.com/phetsims/qa/issues/1102 ...

@arouinfar and I discussed the alignment of icons in the control panels.  

In the published 1.0 version, icons are not right aligned.  For example, in the Systems screen:

<img width="283" alt="screenshot_3391" src="https://github.com/phetsims/hookes-law/assets/3046552/12f2a5b3-c38b-44eb-b8fb-5e56f41daada">

Right aligning all of the icons looks odd and introduces too much space between labels and icons, for example:

<img width="279" alt="screenshot_3392" src="https://github.com/phetsims/hookes-law/assets/3046552/d7dd1440-11fd-4636-b698-05151042a4cf">

So we decided it would be best to turn off right alignment for this sim, and (for checkboxes and radio buttons) maintain a constant space between their text labels and icons, as in the 1.0 version.

**Comment by pixelzoom** [comment]
@arouinfar please review, close if OK.

**Comment by pixelzoom** [comment]
Note that we also decided to reduce the minimum content width to `150` for the top-right panel in each screen.  That was implemented in https://github.com/phetsims/hookes-law/commit/083de1bc49413d9d79b45fb6729745b27e00c545, and can be tested with `?stringTest=dynamic`.

**Comment by arouinfar** [comment]
I tested on main with `stringTest=dynamic` and everything looks good, closing.
