### ISSUE TITLE
Spring Force checkbox is too large

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/hookes-law#101]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1104, on the Systems Screen the Spring Force Checkbox is larger than all the other checkboxes. Sorry I didn't notice when verifying dev test issues. 

**Visuals**
<img width="263" alt="Screenshot 2024-07-08 at 11 26 21 AM" src="https://github.com/phetsims/hookes-law/assets/87318828/2be5ae4b-28da-4fdd-a5ef-492d7138f4de">

**Comment by pixelzoom** [comment]
> Sorry I didn't notice when verifying dev test issues.

My bad.  I introduced this when fixing https://github.com/phetsims/hookes-law/issues/99, which I did not have reviewed.

Fixed in main and 1.1 branches in the above commits.  Labeling for verification in the next RC.

**Comment by pixelzoom** [comment]
Ready for verification in https://github.com/phetsims/qa/issues/1112. Please close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2.
Closing.
