### ISSUE TITLE
Test fix for RTL layout in Firefox 128

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#102]
https://github.com/phetsims/scenery/issues/1643 (Layout of RTL broken in Firefox 128) was patched into the 1.1 release branch, and will need to be tested for 1.1.0-rc.2.

**Comment by pixelzoom** [comment]
Ready for verification in https://github.com/phetsims/qa/issues/1112. Please close if OK.

**Comment by Nancy-Salpepi** [comment]
Fix looks good with FF in rc.2. Closing.
