### ISSUE TITLE
Update screenshots for 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#103]
@arouinfar Do we need to update screenshots for the 1.1. release? Your call.

The only significant changes are in the navigation bar, see comparison of 1.0 and 1.1 below.

1.0:

<img width="1053" alt="screenshot_3413" src="https://github.com/phetsims/hookes-law/assets/3046552/c32ac9f2-5b35-48ff-a931-09802a2dfa5f">

1.1:

<img width="1053" alt="screenshot_3412" src="https://github.com/phetsims/hookes-law/assets/3046552/5c2065e9-6654-4d5c-b993-1d6c2ebdca85">

**Comment by pixelzoom** [comment]
@arouinfar and I discussed this.  She'd like to update the screenshots, and do so before 1.1.0-rc.2.

**Comment by arouinfar** [comment]
@pixelzoom I updated the screenshots on main and 1.1 in the above commits, closing.

**Comment by arouinfar** [comment]
> The only significant changes are in the navigation bar, see comparison of 1.0 and 1.1 below.

Another change we picked up was the appearance of `simName — screenName` in the navbar when using the `screens` query parameter (for screen-specific screenshots). For example:

1.1
<img width="1536" alt="image" src="https://github.com/user-attachments/assets/2b949b28-3377-4e22-af4d-e352650e1107">

1.0
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/7e87a306-972d-490b-87f9-d6f8ff7eef6c">
