### ISSUE TITLE
Drag listener isn’t interrupted when switching scenes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#105]
For RC test https://github.com/phetsims/qa/issues/1104 ...

In https://github.com/phetsims/qa/issues/1104#issuecomment-2226237958, @Nancy-Salpepi reported:

> 
... on the iPad the drag listener isn’t interrupted when switching scenes. For example, on the Systems screen, while moving a slider back and forth with one finger, switching to Series and then back to Parallel will show the slider still moving back and forth.

**Comment by pixelzoom** [comment]
Fixed in the Systems screen by interrupting interactions with the systems when the system type (series vs parallel) is changed.

This was also a problem in the Intro screen when switching between 1 and 2 systems.  Since the Intro screen animates when switching systems, it seems better to interrupt interactions with both systems, rather than to allow continued interaction with system 1 while it's moving. 

Tested in [1.2.0-dev.1](https://phet-dev.colorado.edu/html/hookes-law/1.2.0-dev.1/phet/hookes-law_all_phet.html) on my iPad6 with Safari + iPadOS 17.51.

@Nancy-Salpepi please review.  Leave open for verification in 1.1.0-rc.2.

**Comment by Nancy-Salpepi** [comment]
Looks good on main!

**Comment by pixelzoom** [comment]
Ready for verification in https://github.com/phetsims/qa/issues/1112. Please close if OK.

**Comment by Nancy-Salpepi** [comment]
Fixed in rc.2.
Closing.
