### ISSUE TITLE
Values in DisplacementVectorNode and ForceVectorNode could exist in a Panel

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/hookes-law#11]
The background rectangle in ForceVectorNode and DisplacementVectorNode is updated by

```
      // resize the background behind the value
      backgroundNode.setRect( 0, 0, 1.1 * valueNode.width, 1.1 * valueNode.height, 5, 5 );
      backgroundNode.center = valueNode.center;
```

This could be handled directly by a panel.

This rectangle is also invisible to me on the view, I would not have known this rectangle existed if I did not observe it in the code.  Should this rectangle be more visible?

**Comment by pixelzoom** [comment]
The rectangle is intended to be translucent, and not visible most of the time.  It handles the case where a value is on top of some other user-interface component, making it difficult to read.

For example, here's the displacement (green) value as it overlaps the equilibrium line:

![screenshot_557](https://cloud.githubusercontent.com/assets/3046552/8531980/3d21eef6-23e8-11e5-9f5c-a3bed8de8e68.png)

Here it is what it would look like without the translucent background. Note how the value overlaps with the vertical dashed line.

![screenshot_558](https://cloud.githubusercontent.com/assets/3046552/8532020/94a903e4-23e8-11e5-82cd-c7c2d735858d.png)

Using a panel for this seemed to be a little "heavy", so I went with a lighter-weight approach.

**Comment by pixelzoom** [comment]
Assigning back to @jessegreenberg to see if this explanation is sufficient.

**Comment by pixelzoom** [comment]
I also documented the purpose of the background:

``` js
// translucent background, so that value isn't difficult to read when it overlaps with other UI components 
var backgroundNode = new Rectangle( 0, 0, 1, 1, 5, 5, { fill: 'white', opacity: 0.8 } );
```

**Comment by jessegreenberg** [comment]
This makes sense now, thanks for clarifying.  The documentation is helpful as well, thank you.  Closing.
