### ISSUE TITLE
Public function setPincersOpen could be moved to the inherit block

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/hookes-law#12]
The setPincersOpen() function in RoboticArmNode is declared as a public function inside the RoboticArmNode constructor. Should setPincersOpen() be added to the prototype through the inherit call?

```
    /**
     * Open and close the pincers
     * @param {boolean} pincersOpen
     */
    this.setPincersOpen = function( pincersOpen ) {
      topPincerOpenNode.visible = bottomPincerOpenNode.visible = pincersOpen;
      topPincerClosedNode.visible = bottomPincerClosedNode.visible = !pincersOpen;
    };
```

**Comment by pixelzoom** [comment]
My initial rationale for creating `setPincersOpen` in the constructor was that there will only be 4 instances of RoboticArmNode in the sim, so there is minimal size penalty for adding it in the constructor. And by adding it in the constructor, there were 4 fields (nodes) that could be kept private.  But I can see how this is confusing, so I've moved it to the prototype.

Back to @jessegreenberg for review.

**Comment by jessegreenberg** [comment]
I see, that makes sense.  This looks great though, thanks!  Closing.
