### ISSUE TITLE
create hookes-law-screenshot.png

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#14]
This is the screenshot that will appear on the website.

Assigning to @arouinfar to indicate what configuration of the sim should be shown. You can attach a  screenshot from any dev version to this issue, and I'll create the final screenshot based on the configuration shown.

**Comment by arouinfar** [comment]
Let's go with something like this, @pixelzoom. 
![image](https://cloud.githubusercontent.com/assets/8419308/8578369/a869d528-256b-11e5-9202-3d7065a4a497.png)

**Comment by pixelzoom** [comment]
The process for creating this screenshot is described in the "Steps to publish a public version" section of
https://github.com/phetsims/phet-info/blob/master/sim_deployment.md

> 1. Create a screenshot that is 2048x1344. Generally this is done by taking a screenshot on an iPad 3 or higher (since it has the retina display) with multiple tabs open, then crop the chrome off of it to 2048x1342, then pad the top with 2 pixels of the sim's background color (to 2048x1344) and save as /assets/$SIM-screenshot.png. Eventually, quick and easy creation of this screen shot will be supported through the screenshot feature from the PhET menu, but as of this writing this support doesn't exist.

Since I don't have a retina iPad, looks like I can't do this.

**Comment by samreid** [comment]
I'll take a look.

**Comment by samreid** [comment]
I added the screenshot above.  Please review:
- the name
- the location
- the image dimensions
- the image content

Let me know if there is anything else I should do here.

**Comment by pixelzoom** [comment]
Everything looks great. Thanks @samreid! Closing.
