### ISSUE TITLE
migrate ParametricSpringNode to scenery-phet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#16]
... along with its test harness (the experimental/ subdirectory), which will probably become a screen in the scenery-phet demo app.

**Comment by pixelzoom** [comment]
For anyone who has an opinion...

ParametricSpringNode has an extensive test screen, see hookes-law with "exp" query parameter ("Experimental" screen).  I'm sure this test screen will be useful in the future, so I'd like to move it to scenery-phet with ParametricSpringNode.  If I add it as a screen to the scenery-phet demo, it will be the demo's 4th screen, and is something that can be built and deployed to dev (if that's important).  Should I do that, or should it be a separate app (separate .html file and main.js)?

**Comment by samreid** [comment]
It could be some work to extend our build process to handle multiple html files.  Since I don't want to engage in that work now (and I don't want ParametricSpringNode's test to be a separate repo), perhaps a 4th screen would be best for now.

**Comment by pixelzoom** [comment]
I'm going to hold off on migration to scenery-phet until the optimizations in #3 are completed.

**Comment by pixelzoom** [comment]
... and until API changes in https://github.com/phetsims/hookes-law/issues/9 are completed.

**Comment by pixelzoom** [comment]
API changes in #9 are done, optimization in #3 are done. Time to migrate.

**Comment by pixelzoom** [comment]
This is done.  In addition to migrating ParametricSpringNode to scenery-phet, I also migrated NumberControl and NumberDisplay because (a) they seem to be generally useful, and (b) they are used extensively in the demo for ParametricSpringNode.

 The demo for ParametricSpringNode is now the "Spring" screen in the scenery-phet demo.

NumberControl was added to the "Sliders" screen of the scenery-phet demo in https://github.com/phetsims/scenery-phet/commit/6464219434adebd0e09ede3e88c15500f315148c.

**Comment by pixelzoom** [comment]
All of this code was previously reviewed as part of https://github.com/phetsims/hookes-law/issues/2. There was general agreement (see above) that the ParametricSpringNode demo would be added as a 4th screen in the scenery-phet demo. And migration of NumberDisplay and NumberControl was OK'ed during a Skype conversation.  So I'm going to go ahead and close this issue. If anyone wants to take a peek, go for it.
