### ISSUE TITLE
"look" of the rectangles that spring and robotic arm are attached to

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#17]
The spring and robotic arm are attached to fixed rectangles (WallNode in the code). 

Their fill is currently rgb(210,210,210).

Their dimensions are 25x170 in the single-spring and series systems, 25x300 in the parallel system. At this point it is highly recommended that we stick with these dimensions, so that layout doesn't need to be revisited.

Ideally the look would be something that is easy to create programmatically, so that we don't have to increase html file size, track an asset file, create a license.txt file, deal with crappy-looking images on Firefox, try mipmapping, etc.  If you decide to use image files, I'll need two (one for each dimension).

Assigning to @ariel-phet since he seems to have the strongest feelings about what this should look like.

To keep this sim moving towards publication, the new look (and images, if that's what you decide to use) should be completed by 8/3/2015.

**Comment by pixelzoom** [comment]
We (@arouinfar, @ariel-phet and I) played around with this on 7/16/15.  This email summarizes what we did:

---

Amy, Ariel,

Here’s a version with changes to the walls and robotic arm:

http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-dev.25/hookes-law_en.html

Summary of changes:
• walls have a pseudo-3D bevel
• walls are a darker shade of gray
• robotic arm has a gradient that makes it look like a rounded bar

Chris

**Comment by pixelzoom** [comment]
@ariel-phet said it's OK to take the robotic arm's bar out of the screen icons.

**Comment by arouinfar** [comment]
I think the updated robotic arm looks great! Thanks @pixelzoom.

**Comment by pixelzoom** [comment]
> To keep this sim moving towards publication, the new look (and images, if that's what you decide to use) should be completed by 8/3/2015.

@ariel-phet @arouinfar What is the status of this?

**Comment by ariel-phet** [comment]
@pixelzoom see https://github.com/phetsims/tasks/issues/288 

Looks like something you can draw in code, and it works for me. Feel free to adjust sizes as necessary to make everything work easily for you.

Also feel free to close the above issue once you have seen the basic look.

**Comment by pixelzoom** [comment]
So to clarify...

"As is" for the box that the springs connect to.

Rectangle with no corner radius and vertical gradient for box that the arm disappears into.

Do I have that correct?

**Comment by pixelzoom** [comment]
And should I guess at the gradient colors, or does someone have RGB values?

**Comment by arouinfar** [comment]
Yes, that's correct @pixelzoom. There's also a small red rectangle next to the gray rectangle with the vertical gradient that the arm disappears into. The main color of the rectangle with the gradient should match the robotic arm. I do not have RGB values for the gradient itself.

**Comment by pixelzoom** [comment]
Change request implemented in 
http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-dev.26/hookes-law_en.html

Assigning to @arouinfar for verification.

**Comment by pixelzoom** [comment]
Here's a screenshot for 1.0.0-dev.26.

![screenshot_565](https://cloud.githubusercontent.com/assets/3046552/9048925/222dd9ca-39fa-11e5-8573-c5fd96b49a9d.png)

**Comment by arouinfar** [comment]
Looks good, except for the "adapted from PhET" in the nav bar.

**Comment by pixelzoom** [comment]
"Adapted from PhET" in the menu bar has nothing to do with this issue. It's the new default unless the sim is explicitly built with the PhET brand.  There will be a way to ensure that the PhET brand is the default for dev versions, but that work (being done by @samreid) is not completed yet.

Closing.
