### ISSUE TITLE
Slight points at the top an bottom of spring when thickest

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/hookes-law#20]
If you look carefully at the spring when set to the highest spring constant on the intro screen there are some sharp points at the top and bottom.

To my eye it looks as though these are occurring because of the way the front and back are overlapping (or perhaps the way the gradient is applied?). Not a huge deal, and not sure if much can be done about this issue but seems worth a bit of tweaking/investigating to see if it could be improved/minimized 

![capture](https://cloud.githubusercontent.com/assets/4051174/9242567/aca561c0-4140-11e5-8ee1-993b387d1ced.PNG)

**Comment by pixelzoom** [comment]
Most certainly due to lineCap:'square', with is desirable for the horizontal ends of the spring.  Investigate separate paths for the ends, and use lineCap:'round' for the coil.

**Comment by pixelzoom** [comment]
Set lineCap:'round'.  Using separate paths for the horizontal ends was too much work, and made it difficult to get the gradient fill correct.  Screenshot from "Experimental" screen below.

![screenshot_573](https://cloud.githubusercontent.com/assets/3046552/9262089/987b9748-41cf-11e5-971c-7b229e168a65.png)

Closing.

**Comment by pixelzoom** [comment]
Guess I should get @ariel-phet's approval of this before closing. Look OK?

**Comment by pixelzoom** [comment]
Guess I should get @ariel-phet's approval of this before closing. Look OK? Note that the extreme left and right ends are now rounded, instead of squared off.

**Comment by ariel-phet** [comment]
@pixelzoom - looking good. One tweak...could you layer the left hand side of the spring under the "wall" (so it looks like it is going into the wall)

**Comment by pixelzoom** [comment]
Left-hand side of springs moved under the "walls" in all screens. Closing.

**Comment by pixelzoom** [comment]
For example:

![screenshot_576](https://cloud.githubusercontent.com/assets/3046552/9263005/a6f0c044-41d6-11e5-9cec-0107de737f4b.png)

**Comment by ariel-phet** [comment]
Looks great Closing
