### ISSUE TITLE
Overlap with extreme stringTest

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/hookes-law#22]
Test device: Mac

Operating System: 10.8.5

Browser: Safari 6.2.6

Problem description: Parts of the layout overlap in the Intro screen when the Extremely Long String test is performed.

Steps to reproduce: Run Long string. Go to Intro screen and select to display two springs.

Severity:

Screenshots: 
![screen shot 2015-09-02 at 7 06 00 pm](https://cloud.githubusercontent.com/assets/12610678/9648484/65003f22-51a6-11e5-8e32-afd6afcc576c.png)

Normal: 
![screen shot 2015-09-02 at 7 06 45 pm](https://cloud.githubusercontent.com/assets/12610678/9648488/6c546a64-51a6-11e5-8a12-2abd97118e90.png)

Troubleshooting information (do not edit):
Name: SomeExtremelyLongStringThatWouldLikelyBreakAnythingDidNot
URL: http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-dev.29/hookes-law_en.html?stringTest=SomeExtremelyLongStringThatWouldLikelyBreakAnythingDidNot
Version: 1.0.0-dev.29 2015-09-02 17:09:44 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/6.2.6 Safari/537.85.15
Language: en-us
Window: 1122x548
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.16.74)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"1db622f9","branch":"master"},"babel":{"sha":"696f7588","branch":"master"},"brand":{"sha":"f2c42d7b","branch":"master"},"chipper":{"sha":"e0747524","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"hookes-law":{"sha":"12486758","branch":"master"},"joist":{"sha":"27d92033","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"3cebb2ae","branch":"master"},"scenery":{"sha":"7379d318","branch":"master"},"scenery-phet":{"sha":"b05ed319","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"9dbeaf88","branch":"master"}}

**Comment by pixelzoom** [comment]
@ariel-phet Perhaps I'm not clear on the requirements for i18n testing. I thought the requirement was to make sure the layout looked OK for 'stringTest=double', which I believe it does. This particular case is very unlikely, but I guess you want me to spend time on it, since you assigned it to me.

**Comment by ariel-phet** [comment]
@pixelzoom - I think for i18n testing @samreid had suggested the "extremely long string test to see if anything was not revealed" much like the extremely short string test. Shouldn't things scale down if the strings get very long, or at least not cause this odd overlap?

Happy to punt if you think it is not worth it.

**Comment by pixelzoom** [comment]
This is a general problem with PhET's current methodology of applying the 'stringTest' query parameter to all strings, as detailed in https://github.com/phetsims/chipper/issues/336.

In the case reported here, value readouts like '0 N' are converted to extremely long strings. That will _never_ happen, and isn't something we should have to address in layout code.  But the way that the stringTest query parameter is applied causes this to happen, and possibly masks legitimate issues. We'll discuss the general issue at a developer meeting.

In the meantime... To address this specific issue, I've limited the width of all value displays. Here's a sample screenshot:

![screenshot_595](https://cloud.githubusercontent.com/assets/3046552/9689766/7125f7b0-52f5-11e5-9009-55e51f7a0221.png)

**Comment by samreid** [comment]
> In the case reported here, value readouts like '0 N' are converted to extremely long strings. That will never happen

Perhaps stringTest=double is a better standard for testing?

**Comment by pixelzoom** [comment]
> Perhaps stringTest=double is a better standard for testing?

That's what I thought the standard was, see https://github.com/phetsims/hookes-law/issues/22#issuecomment-137599016.

To be discussed in phetsims/chipper#336.

Re-closing this issue.
