### ISSUE TITLE
Pincher does not release when dragged to 0

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/hookes-law#23]
Test device: iPad 2

Operating System: iOS 8.3

Browser: safari

Problem description: When the slider is dragged or clicked to F=0, the pincher will release the spring. However if you drag the pincher to the 0 position, it does not release. This seems inconsistent.

Steps to reproduce: return pincher to f=0 by dragging the pitcher itself. Release pincher. 

Severity:

Screenshots: 
![image](https://cloud.githubusercontent.com/assets/12610678/9689218/e1a65dd0-52f1-11e5-838c-0cdea5562b5e.jpg)

Troubleshooting information (do not edit):
Name: ‪Hooke's Law‬
URL: http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-dev.29/hookes-law_en.html
Version: 1.0.0-dev.29 2015-09-02 17:09:44 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"1db622f9","branch":"master"},"babel":{"sha":"696f7588","branch":"master"},"brand":{"sha":"f2c42d7b","branch":"master"},"chipper":{"sha":"e0747524","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"hookes-law":{"sha":"12486758","branch":"master"},"joist":{"sha":"27d92033","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"3cebb2ae","branch":"master"},"scenery":{"sha":"7379d318","branch":"master"},"scenery-phet":{"sha":"b05ed319","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"9dbeaf88","branch":"master"}}

**Comment by ariel-phet** [comment]
@elisemorgan - this was a conscious design decision. If you are still in contact with the slider/arm and bring it to zero it still grips. This would be like you holding the spring with your hand but applying no force. We noticed that if you drag through zero and it released it felt odd an unnatural.

**Comment by ariel-phet** [comment]
@arouinfar - it would be good to note the reasons for this decision in the teacher tips.

**Comment by arouinfar** [comment]
Will do @ariel-phet!

**Comment by arouinfar** [comment]
Taken care of in issue #31, so closing.
