### ISSUE TITLE
check visibility of lines in classroom situations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#24]
From @patricialoeblein via email:

One potential improvement: I don’t have an interactive board anymore, but I wonder if you have been able to check the boldness for the lines and displacement vector displaced on an interactive board and viewed from the back row of a classroom. Remember that these boards absorb a significant amount of light energy. I think that the displacement is bold enough, but the  lines seemed thin to me. I made a comparison using Graphing lines (see attached). No need to reply – just giving my unsolicited opinion.

![hooke_graphing_lines](https://cloud.githubusercontent.com/assets/3046552/9738706/fefe74d8-5609-11e5-8d7d-f94e8c108059.jpg)

**Comment by patricialoeblein** [comment]
(Thanks for making the issue Chris.) The lines to which I am referring are on the energy scene. The potential energy (blue) and applied force (red) lines. Also, the green displacement indicator  on the x axis of those graphs looks more thin than the vector representation; I think if it matched the displacement vector the relationship would be more strong.

**Comment by arouinfar** [comment]
Thanks for your feedback @patricialoeblein, and thanks for creating the issue @pixelzoom. One possible solution would be to increase the stroke weights by 1pt. I will take a look at this sim on the projector, and also discuss this issue with @ariel-phet when I see him tomorrow.

**Comment by pixelzoom** [comment]
The green displacement vector and the green line on the x-axis of the graphs do in fact have the same line width (3).

FYI... Here are the line widths used for the graphs:

All graphs:
• x & y axes = 1
• tick marks = 1
• leader (dashed) lines = 1 (shown when "Values" is checked)
• displacement (green) line = 3

Energy XY plot:
• energy (blue) parabola = 2  

Force XY plot:
• force (red) line =2

Potential Energy bar graph:
• x axis = 0.25 (as requested, to deemphasize this axis)

Imo, I think it would be appropriate to increase the line width of force (red) and energy (blue) to 3. See screenshots below, with lineWidth=3. But I don't know if this is sufficient to address @patricialoeblein's concerns, or if there are other elements that need to be tweaked for classroom use.

![screenshot_604](https://cloud.githubusercontent.com/assets/3046552/9745638/61a0a04a-5630-11e5-9521-cb6584bd3174.png)
![screenshot_605](https://cloud.githubusercontent.com/assets/3046552/9745639/65159604-5630-11e5-9b68-c5252efa1465.png)

**Comment by arouinfar** [comment]
Thanks for the screenshots @pixelzoom! I agree that increasing the Force and Energy curves to 3pt would be a good start.

**Comment by pixelzoom** [comment]
OK, I'll commit lineWidth=3 for the force and energy curves.

**Comment by patricialoeblein** [comment]
I thought maybe the displacement vector and line were the same size, but couldn't figure out a good way to check. I imagine the black axis line makes the green line appear different that on a white background. The new images with the width of of 3 for the curves look good. Maybe now that all are the same size the displacement vector will be more notable too. Thanks for the changes.

**Comment by patricialoeblein** [comment]
And for testing on an interactive white board - there have been discussions about PhET acquiring one, perhaps now that I no longer have a classroom, the need is more pressing?

**Comment by pixelzoom** [comment]
> I imagine the black axis line makes the green line appear different that on a white background. 

That and the fact that the green line doesn't have an arrow head.

**Comment by arouinfar** [comment]
@patricialoeblein As far as I know there isn't currently a discussion about acquiring an interactive white board, though maybe this is something we could bring up at a status meeting. My plan was to take the projector down to the cookie room and see what the sim looked like from the back of the room with the lights turned on.

**Comment by pixelzoom** [comment]
Recommended to send the whiteboard issue to @kathy-phet as a topic for discussion at the next status meeting.

**Comment by patricialoeblein** [comment]
My experience with using the projector in the cookie room is that it only somewhat indicates how a sim will look in a classroom. In a normal classroom, there is more light and also the distance from students is more great. A better test might be the lecture hall.

**Comment by arouinfar** [comment]
@patricialoeblein not sure if I can access the lecture halls, but I can try. 

Will do, @pixelzoom.

**Comment by arouinfar** [comment]
@patricialoeblein would you be able to Skype into status next week (9/24) to add to the discussion around acquiring an interactive white board?

**Comment by patricialoeblein** [comment]
Yes I can join the meeting. I will be on Skype 10-11:30 on 9/24 unless I see a change in the times.

**Comment by arouinfar** [comment]
Sounds good @patricialoeblein! I'll ask KP to put it on next week's agenda. We'll mostly likely discuss it at the beginning of status, so it's up to you whether or not you want to stay for the entire meeting.

**Comment by arouinfar** [comment]
I'm going to go ahead and close this issue since the discussion of acquiring a smart board for testing is tangential to Hooke's Law. 

@pixelzoom no need to make any further changes. The sim looks fine when projected on a regular screen.
