### ISSUE TITLE
Slight shrinking of values text/force vector/displacement above 380 N on Energy screen

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/hookes-law#27]
Test device: win 7 desktop

Operating System: Win 7 64 bit

Browser: Chrome (also seen on FF)

Problem description: on the energy screen the values readout on force, as well as the vector shrinks slightly when go above around 380 N.

Steps to reproduce:
1. Open Energy Screen
2. Check values, displacement, applied force
3. Set spring constant to 400 N
4. Move displacement back and forth near 1.000 m maximum
5. You will say significant change in size of displacement readout under the spring (but not on the graph), the Force readout and vector also shrink around 380 N and above but not as noticeably as the displacement

Severity: minor

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Hooke's Law‬
URL: http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-rc.1/hookes-law_en.html
Version: 1.0.0-rc.1 2015-10-01 21:44:56 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Language: en-US
Window: 1920x955
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"90798ec9","branch":"master"},"babel":{"sha":"931afbf1","branch":"master"},"brand":{"sha":"f2c42d7b","branch":"master"},"chipper":{"sha":"fc81a64e","branch":"master"},"dot":{"sha":"428a9836","branch":"master"},"hookes-law":{"sha":"e082cc68","branch":"1.0"},"joist":{"sha":"4a72198b","branch":"master"},"kite":{"sha":"fe8d3c5c","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"acbbf59b","branch":"master"},"scenery":{"sha":"317e459d","branc

**Comment by ariel-phet** [comment]
@pixelzoom - this is pretty minor (but noticeable) would be good to investigate

**Comment by arouinfar** [comment]
I also observed this behavior in OSX 10.9.5/Safari 9. The displacement value starts to shrink around +/- 0.65m, regardless of the value of the spring constant.

**Comment by arouinfar** [comment]
This also happens on the Intro and Systems screens once the displacement vector becomes sufficiently long (again, around 0.65m). No shrinkage of the Applied Force value has been observed on these screens.

Intro:
![image](https://cloud.githubusercontent.com/assets/8419308/10376477/436eaa16-6dbb-11e5-9990-f47c16ba7017.png)

Systems: 
![image](https://cloud.githubusercontent.com/assets/8419308/10376468/3c7895aa-6dbb-11e5-95f3-bc352b6e61b2.png)

**Comment by pixelzoom** [comment]
This was an i18n error. The `maxWidth` was being applied to the vectors instead of to the values on the vectors. Fixed in above commits (master and 1.0 branch), will appear in next RC version.
