### ISSUE TITLE
1.0.0 publication items

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/hookes-law#35]
**Design/Admin**
- [x] Rosetta test (Opening sim to trusted translators for beta)
- [x] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [x] Review process with QA team.

**Comment by arouinfar** [comment]
Reassigning to @ariel-phet until Rosetta beta testing is done.

**Comment by ariel-phet** [comment]
Back to you @arouinfar  to check off sim primer :). Super exciting you already have translations!

**Comment by ariel-phet** [comment]
Primers are being dealt with in separate issues, going to go ahead and close this issue.
