### ISSUE TITLE
Add sim to NSDL Science Literacy Maps?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/hookes-law#36]
Question for @patricialoeblein -- Should we continue to tag our sims with keys from the NSDL Science Literacy Maps, or is this out-of-date?

If we should continue to add NSDL keys and benchmarks to the sims, please reassign this issue to me and I will take care of tagging Hooke's Law.

**Comment by patricialoeblein** [comment]
Yes continue to keep NDSL up to date. Many people are not going to NGSS and this resource is used by many many. We have not yet decided how we are going to add metadata for NGSS, but we do have identification for PEs ready for internal review. KP will be sharing.

Trish Loeblein
Patricia.Loeblein@colorado.edumailto:Patricia.Loeblein@colorado.edu
PhET K12 Specialist http://phet.colorado.edu/

**Comment by ariel-phet** [comment]
@arouinfar - lets sit down sometime together and I will show you how to navigate the NSDL Literacy Maps

**Comment by arouinfar** [comment]
Thanks for your input @patricialoeblein, and thanks for your offer @ariel-phet! I spent some time playing with the NSDL Literacy map, and was able to tag Hooke's Law. Closing.
