### ISSUE TITLE
PhET-iO instrumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#38]
In 12/21/2015 email, @ariel-phet wrote:

> Kathy and I just discussed, and here is the current thought:
> 
> When Sam give's the green light that together is in a good place, we would like you to work on outfitting the first screen of Hooke's Law. Kathy was thinking about 10 hours of your time, so if outfitting goes quickly, feel free to go further in the sim, but with the first screen as the clear goal. If outfitting does not go quickly (obvious possibility), lets touch base as to progress after 10 hours.

**Comment by pixelzoom** [comment]
I'd like to see these issues addressed before this work proceeds:

- [x] https://github.com/phetsims/beers-law-lab/issues/129
- [x] https://github.com/phetsims/beers-law-lab/issues/131
- [x] https://github.com/phetsims/beers-law-lab/issues/133

(NOTE: All the of the above have been addressed and closed.)

**Comment by pixelzoom** [comment]
At 1/7/16 status meeting, this task was deferred indefinitely.

**Comment by pixelzoom** [comment]
This is back on, assigned to @samreid and me to work on.  @kathy-phet is getting info on what needs to be instrumented.

**Comment by pixelzoom** [comment]
I did a few things to prepare for instrumentation: #48, #49, #50, #51.

**Comment by pixelzoom** [comment]
I did a few things to prepare for instrumentation: #48, #49, #50, #51.

@samreid let me know if there's any other "general" things that I should consider.

**Comment by samreid** [comment]
Instrumentation looks like it is going well so far--I'm around for a while if you'd like me to tag along.

**Comment by kathy-phet** [comment]
Is Chris doing this then?
K

Sent from my iPhone

On Jun 7, 2018, at 5:37 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


Instrumentation looks like it is going well so far--I'm around for a while if you'd like me to tag along.

**Comment by pixelzoom** [comment]
Basic instrumentation is done (tandems propagated). Ready to instrument specific Properties, etc. when @kathy-phet provides requirements.

**Comment by pixelzoom** [comment]
In the `State` wrapper, when switching to 2 systems, the top system doesn't move to it's new position, see screenshot below.  This is handled by a TWEEN animation in IntroScreenView.

![screenshot_669](https://user-images.githubusercontent.com/3046552/41131466-2eb8c3d2-6a79-11e8-9754-2a7bf3bd1d22.png)

**Comment by samreid** [comment]
For labeled UI components, I'd recommend naming the tandem to match the english text that appears on the label.  For instance, the top radio button is labeled "Bar Graph", but the tandem is `energyBarRadioButton`--it should be `barGraphRadioButton`.  This may include renaming vars or (lowercase) properties to match the tandems, where appropriate.

Also, I've committed initial work to phet-io-wrapper-hookes-law-energy, please be aware of the work there and update/change phetioIDs if they are changed in the simulation.

**Comment by pixelzoom** [comment]
I renamed tandems, types and enums to match the labels that appear on controls.  For example, for the "Force Plot" radio button, the tandem is now `"forcePlotRadioButton"`, the enum value is `"forcePlot"`, and the type is `ForcePlot`.   I did this for the "Bar Graph", "Energy Plot" and "Force Plot" radio buttons.  I review all calls to `createTandem` and didn't see any other cases where this needed to be done.  @samreid feel free to take a peek.

**Comment by pixelzoom** [comment]
In the above commit, I instrumented the model Properties in RoboticArm and Spring.  Questions and concerns for @samreid to review:

- [x] After doing this, `phet-io-wrapper-hookes-law-energy` now fails with `Assertion failed: cannot start event while event is in progress` when dragging either the arm or the displacement slider.

- [x] Check my use of the `units` option.

- [x] I was unclear on how to instrument DerivedProperty.  Looks like `phetioType` is required, but there was nothing to validate that, and omitting resulted in a hard failure, see https://github.com/phetsims/tandem/issues/56.   Did I end up doing this correctly?

- [x] Is the convention to group phet-io modules with a `// phet-io modules` comment?  I looked for examples, but didn't see any consistent pattern.  See https://github.com/phetsims/phet-io/issues/1331  
(EDIT: Convention is now `// ifphetio`.)

**Comment by samreid** [comment]
> After doing this, `phet-io-wrapper-hookes-law-energy` now fails with `Assertion failed: cannot start event while event is in progress` when dragging either the arm or the displacement slider.

Tracked in https://github.com/phetsims/hookes-law/issues/52, and another solution is in place, see https://github.com/phetsims/tandem/issues/57

> Check my use of the `units` option.

Usage of units looks good, and appears properly in studio.

> I was unclear on how to instrument DerivedProperty.  Looks like `phetioType` is required, but there was nothing to validate that, and omitting resulted in a hard failure, see https://github.com/phetsims/tandem/issues/56.   Did I end up doing this correctly?

Work is being done in https://github.com/phetsims/tandem/issues/56

> Is the convention to group phet-io modules with a `// phet-io modules` comment?  I looked for examples, but didn't see any consistent pattern.  See https://github.com/phetsims/phet-io/issues/1331  
(EDIT: Convention is now `// ifphetio`.)

Addressed as described in preceding comments.

**Comment by pixelzoom** [comment]
Further work on instrumentation has moved to #58.

Closing.
