### ISSUE TITLE
Edge full screen is broken

### ISSUE THREAD

**Issue by phet-steele** [phetsims/hookes-law#39]
@jonathanolson I only see this in the maintenance release (2/22) for phetsims/tasks/issues/523. Full screen results in this:

![screenshot 1](https://cloud.githubusercontent.com/assets/5863899/13264397/3ded8f3a-da2b-11e5-8661-73bfbf0a898f.png)
There's some white space at the bottom, too (trust me, there's no line break between the screenshot and this text).

**Comment by jonathanolson** [comment]
Can reproduce with Chrome and rootRenderer=canvas. Investigating.

**Comment by jonathanolson** [comment]
Errors out with console open, leads me to believe patching https://github.com/phetsims/scenery/commit/aacceb9a2835e1803c4b1c88bd8c112e70a16314 may fix the problem.

**Comment by phet-steele** [comment]
@jonathanolson fixed here http://www.colorado.edu/physics/phet/dev/olsonjb/maintenance2/hookes-law_en.html

**Comment by pixelzoom** [comment]
Reopening. 

As with #40, I'd like to know how this was patched - it doesn't resemble any PhET process that I'm familiar with. 

There's also a total absence of information here on what the problem was, or why phetsims/scenery@aacceb9 fixed the problem.

**Comment by pixelzoom** [comment]
There's also a total absence of information here on what the problem was, or why phetsims/scenery@aacceb9 fixed the problem.

**Comment by pixelzoom** [comment]
Discussed on Skype with @jonathanolson. Future verifications will be done using a dev version on the release branch, not a deploy into a developer-specific directory.

**Comment by pixelzoom** [comment]
This fix was published in 1.0.2.
