### ISSUE TITLE
Edge equilibrium dashed line

### ISSUE THREAD

**Issue by phet-steele** [phetsims/hookes-law#40]
@jonathanolson @ariel-phet this again, for the Equilibrium line: phetsims/scenery/issues/510

![hookeequil](https://cloud.githubusercontent.com/assets/5863899/13264556/f764ce42-da2b-11e5-9c5a-79d65254ca81.PNG)

It's supposed to be dashed, seen in Edge (20+) in both the production version and 2/22 maintenance releases (phetsims/tasks/issues/523).

**Comment by jonathanolson** [comment]
@ariel-phet, I also recommend patching for this sim.

**Comment by phet-steele** [comment]
And these lines (at specific values like this):
![hookegraph](https://cloud.githubusercontent.com/assets/5863899/13264738/d84389a8-da2c-11e5-80c2-509bdb7ddf38.PNG)

Supposed to be:
![hookegraph2](https://cloud.githubusercontent.com/assets/5863899/13264768/fa3693c0-da2c-11e5-8ab5-7fe8cefa1c69.PNG)

**Comment by ariel-phet** [comment]
Feel free to proceed @jonathanolson

**Comment by phet-steele** [comment]
@jonathanolson fixed here http://www.colorado.edu/physics/phet/dev/olsonjb/maintenance2/hookes-law_en.html

**Comment by pixelzoom** [comment]
Reopening. 

I'd like to know how this was patched - it doesn't resemble any PhET process that I'm familiar with. Eg what's going on with the non-standard "maintenance2" location in the URL above?

There's also a total absence of information here on what the problem was and how it was fixed.

**Comment by pixelzoom** [comment]
There's also a total absence of information here on what the problem was and how it was fixed.

**Comment by pixelzoom** [comment]
Discussed on Skype with @jonathanolson. Future verifications will be done using a dev version on the release branch, not a deploy into a developer-specific directory.

**Comment by pixelzoom** [comment]
This fix was published in 1.0.2.
