### ISSUE TITLE
This sim does not have an assets file yet

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/hookes-law#5]
Assets file is missing.  No image files are used in this sim, so no assets are necessary, but hookes-law-screenshot.png will eventually be placed here.

**Comment by pixelzoom** [comment]
It's not possible to have an empty directory checked into git.  The assets directory will exist when there's something to put in it.

**Comment by pixelzoom** [comment]
I'm going to close this issue, since creating the screenshot is on my TODO list.
