### ISSUE TITLE
State wrapper: wrong position for top system

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#53]
Related to #38.

In the `State` wrapper, _Intro_ screen, when switching to 2 systems, the top system doesn't move to it's new position, see screenshot below.  This is handled by a TWEEN animation in IntroScreenView.

![screenshot_669](https://user-images.githubusercontent.com/3046552/41131466-2eb8c3d2-6a79-11e8-9754-2a7bf3bd1d22.png)

**Comment by pixelzoom** [comment]
In case this is somehow related to the TWEEN animation...  Replacing TWEEN is the subject of https://github.com/phetsims/hookes-law/issues/46.

**Comment by pixelzoom** [comment]
The top system node is currently moved by changing its `centerY` directly.  Do we need to add an intermediate Property in order to support record/playback of this animation?

**Comment by pixelzoom** [comment]
I added `system1CenterYProperty` in the above commit, and this issue is no longer present in the "State" wrapper.  @samreid please review, to verify that this is the preferred way of addressing this.

**Comment by samreid** [comment]
@pixelzoom the strategy you used is the preferred strategy for addressing this.  But I'd like to point out the alternative strategy so you are aware of it, in case it comes up elsewhere.  The alternative strategy would be to create an IO type IntroScreenViewIO, then define toStateObject/fromStateObject for it and pass it a tandem.  Then it could serialize any of its (lower-case) properties directly.

Just to clarify, the strategy you used of creating an instrumented sub-Property works best in this case.  You would only use the other strategy when creating an instrumented sub-Property doesn't work (I'm not exactly sure when that would be.)

OK to close when acknowledged.
