### ISSUE TITLE
Improvement to displacement slider - semi-snappy slider

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/hookes-law#54]
In working with this client, they noted that it is hard to reproduce nice values with the displacement sliders currently. We have often used a strategy lately to make improvements to this behavior, and it would be nice to apply that strategy here to do a semi-snappy slider with 0.05 m jumps (so 40 settings over the length of the slider) and then using the tweakers if you want to do smaller jumps and get to 0.051 for instance. 

This would allow easier testing of doubling, and nice values. like 0.2 to 0.4. Etc. 

@arouinfar - Can you take a look, and see what you think? I believe this strategy works well here, and we would likely have done it if we designed this sim today.

**Comment by pixelzoom** [comment]
@kathy-phet please clarify.  

(1) You said "displacement sliders".  This sim has only one displacement slider, on the Energy screen.   

(2) Model quantities are already constrained to the number of decimal places shown below. And as I recall, we spent a great deal of time choosing these values.  Do we really want to revisit this?

HookesLawConstants.js:

```js
    // number of decimal places for quantities
    SPRING_CONSTANT_DECIMAL_PLACES: 0,
    APPLIED_FORCE_DECIMAL_PLACES: 0,
    SPRING_FORCE_DECIMAL_PLACES: 0,
    DISPLACEMENT_DECIMAL_PLACES: 3,
    ENERGY_DECIMAL_PLACES: 1,
```

**Comment by pixelzoom** [comment]
@kathy-phet please clarify.  

(1) You said "displacement sliders".  This sim has only one displacement slider, on the Energy screen.   Are you referring only to displacement, or other sliders too?  How is this problem specific only to the displacement slider?

(2) Model quantities are already constrained to the number of decimal places shown below. And as I recall, we spent a great deal of time choosing these values.  Do we really want to revisit this?

HookesLawConstants.js:

```js
    // number of decimal places for quantities
    SPRING_CONSTANT_DECIMAL_PLACES: 0,
    APPLIED_FORCE_DECIMAL_PLACES: 0,
    SPRING_FORCE_DECIMAL_PLACES: 0,
    DISPLACEMENT_DECIMAL_PLACES: 3,
    ENERGY_DECIMAL_PLACES: 1,
```

**Comment by pixelzoom** [comment]
And here are the deltas that are currently used for the arrow buttons that are associated with each slider, also from HookesLawContants.js:

```js
    // deltas for controls
    SPRING_CONSTANT_DELTA: 10, // units = N/m
    APPLIED_FORCE_DELTA: 1, // units = N
    DISPLACEMENT_DELTA: 0.001, // units = m
```

**Comment by pixelzoom** [comment]
All of the slider+arrow controls in this sim are implemented using NumberControl, which currently has no way to constrain the slider as @kathy-phet suggested.

**Comment by pixelzoom** [comment]
Note that if you constrain the displacement slider, then you'll also need to constrain the robotic arm, since moving the robotic arm changes the slider value.

**Comment by pixelzoom** [comment]
Note that if we constrain the displacement slider, then we might also need to constrain the robotic arm, since moving the robotic arm changes the slider value.  Or maybe it's OK if the robotic arm operates with the same precision as the arrow buttons?

**Comment by pixelzoom** [comment]
All of the sliders+arrows in this sim are implemented using NumberControl, which does not directly support the type of "snapping" to intervals that @kathy-phet describes (e.g. snapping to 0.05m increments).  I might be able to use option `sliderStartCallback`.

**Comment by kathy-phet** [comment]
Sorry - only the one displacement slide. 

The number of decimals is fine. 

An example would be the sliders in pendulum lab. If you slide them they jump snappy behavior by 0.10, but the tweakers make them jump by 0.01 for more precise look. (This is an approach that Amy has been using more recently in sims, and for which we have turned to for pedagogical reasons of improving ability to do precise doubling and reproducing data more readily). 

Yes, the green robotic control would also need to be semi snappy like the spacing between the balls in gravity and orbits are now. 

I'm not sure what drove the number of decimal places -- except that if the distance is not a nice value they you do need more decimals to get the values you expect.

**Comment by kathy-phet** [comment]
https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_en.html
See this for slider / tweaker example (length).

**Comment by kathy-phet** [comment]
Hopefully Amy can take a look tomorrow, too.

**Comment by pixelzoom** [comment]
I reviewed Pendulum Lab.  The sliders feel jerky to me.  But if that's what you want...  I should be able to use NumberControl `constrainValue` option to constrain the value to specific increments while dragging the slider thumb.

**Comment by pixelzoom** [comment]
@kathy-phet @arouinfar please review [1.1.0-dev.5]().  This version constrains displacement to 0.05m increments when dragging the displacement slider (which appears in the Energy screen only) or the robotic arm (which appears in all screens).   A side-effect of this is that dragging the robotic arm in the first 2 screens results in much larger jumps in applied force value, so you can drag the robotic arm to dial in smaller applied force values.  We could constrain the robotic arm in the Energy screen only, but that might seem odd to the user.   Let me know how you'd like to proceed.

**Comment by pixelzoom** [comment]
@kathy-phet @arouinfar please review [1.1.0-dev.5](https://phet-dev.colorado.edu/html/hookes-law/1.1.0-dev.5/phet/hookes-law_en_phet.html).  This version constrains displacement to 0.05m increments when dragging the displacement slider (which appears in the Energy screen only) or the robotic arm (which appears in all screens).   A side-effect of this is that dragging the robotic arm in the first 2 screens results in much larger jumps in applied force, so you cannot drag the robotic arm to dial in smaller applied force values.  We could constrain the robotic arm in the Energy screen only, but that might seem odd to the user.   Let me know how you'd like to proceed.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. You caught me mid-comment, so I'll instead review the latest dev.

**Comment by arouinfar** [comment]
@pixelzoom @kathy-phet the displacement slider and robotic arm on the Energy screen feel great. I really like the new behavior. It will be much more efficient to set up pedagogically useful experiments.

However, the robotic arm is a bit clumsy on the other screens. Since the arm is snapping to displacement values, and not applied force, the increments can be VERY coarse. For example, when maximizing the spring constant on Intro, the arm snaps to 5 different positions, corresponding to +/-100 N, +/- 50 N, and 0 N. That is simply not enough resolution.

In interviews, students mapped the robotic arm to the slider below it. On the first two screens, they think of moving the arm as changing the applied fore. On Energy, they think of it as changing the displacement. However, it appears that the model always ties the robotic arm to the displacement. If that's the case, then I recommend only applying the snappy behavior on the Energy screen.

**Comment by pixelzoom** [comment]
[1.1.0-dev.6](https://phet-dev.colorado.edu/html/hookes-law/1.1.0-dev.6/phet/hookes-law_en_phet.html) constrains dragging of the robotic arm to 0.05m increments in the Energy screen only.  The other screens have continuous dragging.  @arouinfar please review.

**Comment by arouinfar** [comment]
Looks good to me @pixelzoom, thanks!

**Comment by pixelzoom** [comment]
@arouinfar said:
> .... However, it appears that the model always ties the robotic arm to the displacement. If that's the case, then I recommend only applying the snappy behavior on the Energy screen.

The model is `F = kx`.  The robotic arm is indeed changing displacement, `x` -- why would it change anything else?  Applied force control is changing `F`, and spring constant control is changing `k`.   When one quantity changes, the others are recomputed.

**Comment by pixelzoom** [comment]
Great, thanks @arouinfar.  Closing.  

@kathy-phet feel free to review, reopen if you have any issue with what's been done here.
