### ISSUE TITLE
Instrument the play area panels

### ISSUE THREAD

**Issue by samreid** [phetsims/hookes-law#55]
For #38, we would like to be able to hide the entire slider control *Panel*, not just the contents of the panel, and we would like the content tandem to be nested in the panel tandem.  I'll demonstrate one way to accomplish this for the Energy screen.

**Comment by samreid** [comment]
Please see the hookes-law commit for how this was accomplished.  @pixelzoom can you please review and, if it seems good, apply the same strategy to the other screens?

**Comment by pixelzoom** [comment]
Looks good.  I applied the same pattern to the other panels.  I shortened tandem name (e.g.) "springConstantControlPanel" to "springConstantPanel" throughout.   @samreid Take a peek, close if this looks OK.

**Comment by samreid** [comment]
The change sets look great, closing.
