### ISSUE TITLE
reuse of code for point tool

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#61]
Graphing Lines has a point tool that looks like this:
![screenshot_717](https://user-images.githubusercontent.com/3046552/44418354-6455e280-a535-11e8-87d7-54ab133a2be3.png)

Graphing Quadratics has a point tool that is similar, but has a different "crosshair" sensor:
![screenshot_718](https://user-images.githubusercontent.com/3046552/44418387-7df72a00-a535-11e8-92c7-78446647c0f7.png)

To implement the point tool in Graphing Quadratics, `PointToolNode` was copied from graphing-quadratics, then modified, with this TODO in the code:

`//TODO Copied from GRAPHING_LINES/common/view/PointToolNode`

The implementations are very similar, but factoring something out to be used by both graphing-lines and graphing-quadratics would be a bit forced/unnatural. 

Options:
(1) Use the new design in both graphing-quadratics and graphing-lines.
(2) Factor out common code, even if it's forced/unnatural.
(3) Live with code duplication.

Option (1) is best, if that's acceptable to the designer.  @amanda-phet what do you think?

**Comment by arouinfar** [comment]
@pixelzoom I think you have the wrong repo.

**Comment by pixelzoom** [comment]
Oops, thanks @arouinfar.  Guess I'm working on too many things at once :)

Moved to https://github.com/phetsims/graphing-quadratics/issues/18.
