### ISSUE TITLE
Memory leak testing for 1.1 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#67]
For #91.

**Comment by pixelzoom** [comment]
See memory test for 1.1.0-dev.18 in https://github.com/phetsims/qa/issues/1102#issuecomment-2197507783.

@KatieWoe said:
> Memory test looked ok. If there is a leak it is small.

**Comment by pixelzoom** [comment]
After addressing dev-test issues for https://github.com/phetsims/qa/issues/1102, here is the result of memory testing for the PhET brand.  Heap size stablizes at ~96MB, and the heap size was observed to go down twice (Snapshots 7 & 9).  So there no indication of any memory leak.

<img width="202" alt="screenshot_3398" src="https://github.com/phetsims/hookes-law/assets/3046552/f5a60f7c-8651-4769-b7ed-aa8d0338e3cb">

**Comment by pixelzoom** [comment]
Please verify for https://github.com/phetsims/qa/issues/1104, close if OK.

**Comment by Nancy-Salpepi** [comment]
There might be a tiny leak. Heap size did go down or stay the same at some points, but it never seemed to stabilize. Snapshots 11 and 12 were taken 10 minutes apart (all others were taken at one minute intervals).
<img width="263" alt="Screenshot 2024-07-08 at 3 37 13 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/ebaf0dd7-5a26-467a-9edd-9ca34b702d5f">

**Comment by pixelzoom** [comment]
To me, it looks like it stablized ~66 MB.  And since it was ony 1.3 MB different after 20 minutes (Snapshot 10 vs 12) then I doubt there's a leak, or at least any leak that we need to address.  So I'm not going to do any additional work on memory management and will call this done.
