### ISSUE TITLE
Some comments do not extend to 120 characters

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/hookes-law#7]
In the PhET Development Overview, comment style is defined such that 

> Comments should not extend beyond 120 columns, and line breaks should be inserted for multi-line comments just before word that would extend beyond 120th column.  Code lines should also be broken up if they pass 120 columns.

I notice that in files like Spring.js, ParametricSpringControls.js, IntroSystemNode.js, ParallelSystemsNode.js, SeriesSystemNode.js, line breaks are inserted well before the 120th character.

**Comment by pixelzoom** [comment]
120 is an upper limit, there's no requirement to extend each comment line to that limit. I prefer to break lines where it feels most natural and readable.

Closing.
