### ISSUE TITLE
Usability for small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/hookes-law#73]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Arrows to control sliders could have slightly larger pointer areas
* Total and Components Areas overlap on Systems screen

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56158258-d379be80-5f7e-11e9-9d3e-bf4480e7d3c7.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56158259-d379be80-5f7e-11e9-8b34-d5b029283f96.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56158260-d4125500-5f7e-11e9-83f4-ba08f3969ce8.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56158261-d4125500-5f7e-11e9-9960-5631916c81f3.png)

**Comment by arouinfar** [comment]
@pixelzoom here is a proposal for updated pointer areas for Total/Components and the NumberControl tweakers, utilizing the asymmetric dilation added in https://github.com/phetsims/scenery-phet/issues/489.

![image](https://user-images.githubusercontent.com/8419308/56302519-2c6c6280-60f7-11e9-8fb5-dd23e72198d6.png)

**Comment by pixelzoom** [comment]
@arouinfar I've made the adjustments specified in https://github.com/phetsims/hookes-law/issues/73#issuecomment-484151960.  Please review in master.

**Comment by arouinfar** [comment]
👍
