### ISSUE TITLE
use AquaRadioButtonGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#76]
From phetsims/sun#555, convert this sim to use AquaRadioButtonGroup for phet-io.

Use in place of AquaRadioButton in these 2 places:

- [x] `SystemsVisibilityControls`:  This radio button group needs to be disabled when "Spring Force" is unchecked.  AquaRadioButtonGroup currently does not support this.

<img width="233" alt="screenshot_142" src="https://user-images.githubusercontent.com/3046552/74987805-55394480-53f9-11ea-98a4-cf32047ba748.png">

- [x] `EnergyVisibilityControls`: The "Energy" checkbox needs to be associated with the "Force Plot" radio button in the layout.  This is not supported by AquaRadioButtonGroup.  I could create an AquaRadioButtonGroup, then tack the "Energy" checkbox onto the bottom. But that doesn't feel very robust -- if the order of radio buttons is ever changed, then the "Energy" checkbox will be in the wrong place.

<img width="250" alt="screenshot_141" src="https://user-images.githubusercontent.com/3046552/74987801-52d6ea80-53f9-11ea-86dd-ad8f1125886c.png">

**Comment by pixelzoom** [comment]
`SystemsVisibilityControls` is blocked by https://github.com/phetsims/sun/issues/582.

`EnergyVisibilityControls` is blocked by https://github.com/phetsims/sun/issues/583.

**Comment by zepumph** [comment]
https://github.com/phetsims/sun/issues/582 has been completed and closed.

**Comment by pixelzoom** [comment]
`SystemVisibilityControls` is done in the above commit.

`EnergyVisibilityControls` is still blocked by phetsims/sun#583.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/sun/issues/583#issuecomment-610571992:

> More notes from 3/26/20 dev meeting... It was suggested that the problem with `BEERS_LAW_LAB/ViewsControl` might be resolved by redesigning it. We should certainly consider that. But my opinion is that this is a perfectly valid design, there's nothing wrong with it, and switching to an inferior design to avoid the problem is not a "solution".

This also applies to `HOOKES_LAW/EnergyVisibilityControls`.

**Comment by pixelzoom** [comment]
For EnergyVisibilityControls... Since the "Energy" checkbox appears below the radio button group, I decided to convert the radio buttons to use AquaRadioButtonGroup.  The "Energy" check box does not appear as a child of the "Force Plot" radio button in the Studio tree, but that seems OK to me -- we'll see if it comes up in PhET-iO redesign #69.

Closing.
