### ISSUE TITLE
Add support for dynamic locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#81]
This is ~25% completed.

**Comment by pixelzoom** [comment]
Done. Ready for review when work resumes on this sim.

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/1102 and related to https://github.com/phetsims/hookes-law/issues/88, the touch area for the Values checkbox doesn't expand with ?stringTest=dynamic:
<img width="245" alt="Screenshot 2024-06-28 at 7 56 48 AM" src="https://github.com/phetsims/hookes-law/assets/87318828/59e07b5e-ab37-4f57-aeab-636821fc1f21">

**Comment by Nancy-Salpepi** [comment]
A couple of differences I see when comparing to the published version:
-  On the Energy screen, the Energy Checkbox has shifted to the right 
- On the Energy screen, when at max values the Applied Force arrow now touches the panel. 

Dev Version vs. Published:

<img width="359" alt="Screenshot 2024-06-28 at 8 30 10 AM" src="https://github.com/phetsims/qa/assets/87318828/6d07670f-2fbb-4f2f-8be7-3d49426dd64f"> <img width="359" alt="Screenshot 2024-06-28 at 8 29 58 AM" src="https://github.com/phetsims/qa/assets/87318828/eee656ba-788b-4a92-bf88-2e70e9f09ae4">


 Also with ?stringTest=dynamic, the text background of the Applied Force Value can overlap the panel slightly when Displacement =1.
<img width="259" alt="Screenshot 2024-06-28 at 12 06 40 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/7cba801b-e15d-497d-bf46-1590ce61dce7">

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/1102 in locales other than English, the bottom panel sizes are slightly different heights.
Here are the Spring and Applied Force panels for the screens 1&2 in Hebrew:
<img width="527" alt="Screenshot 2024-06-28 at 3 36 30 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/476c0825-44d7-4264-b416-924bd20d1ea8">
<img width="896" alt="Screenshot 2024-06-28 at 3 39 59 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/a418a80a-9760-432f-a8ad-62001145980e">
And here are the Spring and Displacement panels for screen 3 in Hebrew:
<img width="649" alt="Screenshot 2024-06-28 at 3 48 27 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/519b20d7-055c-4b67-b845-38f9b6826a9c">

**Comment by jessegreenberg** [comment]
A couple of notes from https://github.com/phetsims/qa/issues/1102 regarding layout changes, possibly from dynamic locale:

- [ ] The layout has changed and now this text has scaled down: 
     <img width="214" alt="image" src="https://github.com/phetsims/hookes-law/assets/8419308/83cbd360-aafd-43d0-8e9d-ed016654152a">

- [ ] Shorter strings can move the images next to them, which didn't happen in published. Both dynamic and non-dynamic locale seems impacted. @Matthew-Moore240 noted it is a little easier to see with ?stringTest=dynamic. 

     https://github.com/phetsims/hookes-law/assets/8419308/0b44afd3-6031-4109-99e9-a37ffa05376d

**Comment by pixelzoom** [comment]
There were a bunch of unrelated issues reported in this issue.  To make them easier to verify by QA, I've moved them to their own issues, linked above.
