### ISSUE TITLE
Move the phet-io-wrapper-hookes-law-energy into phet-io-sim-specific

### ISSUE THREAD

**Issue by samreid** [phetsims/hookes-law#82]
From https://github.com/phetsims/phet-io-sim-specific/issues/1, we should move the phet-io-wrapper for hookes law into the phet-io-sim specific repo.  Please maintain history.  Unassigned until we work on this sim again.

**Comment by zepumph** [comment]
We should make sure that this blocks the next release, this way we won't keep a dependency on that repo (phet-io-wrapper-hookes-law-energy) for longer than we need to.

**Comment by pixelzoom** [comment]
@samreid @zepumph We're doing a new release of this sim, see https://github.com/phetsims/hookes-law/issues/91.  That release will not include PhET-iO.  But should we address this issue now?

**Comment by zepumph** [comment]
Yes great idea. At the very least we should publish the new version without the repo "phet-io-wrapper-hookes-law-energy" in the package.json. Thanks for assigning.

**Comment by zepumph** [comment]
Working on this now.

**Comment by zepumph** [comment]
Ok. The dependency on phet-io-wrapper-hookes-law has been removed. We now have the content in phet-io-sim-specifc, and I tested that it was deployed on phet-io build. This issue is ready to close, and we can continue with https://github.com/phetsims/phet-io-wrapper-hookes-law-energy/issues/7.
