### ISSUE TITLE
Create a dev test of hookes-law

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/hookes-law#86]
During planning meeting today I was asked to prepare a dev test of hookes-law. We are going to republish the sim with PhET brand off of main. Republishing the sim will make it easier to maintain.

This issue is to track progress and take notes while @pixelzoom is away.

Note that #80 may need to be renamed or closed. This dev test is likely ahead of a 1.1 release with only PhET brand.

**Comment by jessegreenberg** [comment]
QA issue created at https://github.com/phetsims/qa/issues/1102.

Sim version is 1.1.0-dev.18.

**Comment by jessegreenberg** [comment]
Assigning @pixelzoom so he is aware, but this can probably just be closed.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg. Closing.
