### ISSUE TITLE
Pointer areas are longer than touch areas in many places

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/hookes-law#88]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1102, in many places the pointer areas have a greater length than the touch areas. On the Energy Screen it looks like the graph/plot radio buttons have 2 touch areas. 

**Visuals**
<img width="288" alt="Screenshot 2024-06-27 at 9 10 19 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/89d2af42-ce5f-44dc-88b0-584484ebc3cb">
<img width="288" alt="Screenshot 2024-06-27 at 9 12 50 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/137d3960-772e-4d49-bde6-a54b61d44e7b">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please review, close if OK.  Note the decision NOT to right-align icons in https://github.com/phetsims/hookes-law/issues/100.

Intro screen:
<img width="249" alt="screenshot_3394" src="https://github.com/phetsims/hookes-law/assets/3046552/5b74a25c-6a60-4ce3-a1d0-fe9bfa83b8c4">

Systems screen:
<img width="264" alt="screenshot_3395" src="https://github.com/phetsims/hookes-law/assets/3046552/276f70cc-9237-4c5e-adc4-f8ae7616b3cd">

Energy screen:
<img width="244" alt="screenshot_3396" src="https://github.com/phetsims/hookes-law/assets/3046552/846308dd-b571-4bee-b863-df1e98a47990">

**Comment by Nancy-Salpepi** [comment]
The radio button group on the Energy screen still seems to have 2 different touch areas--one that is the same size as the pointer area and a second one that is wider....you can see it in your screenshot but here is a zoomed-in view:
<img width="748" alt="Screenshot 2024-07-02 at 3 32 00 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/a69432c7-eea2-4570-a0d7-6e4de6ceaa91">

**Comment by pixelzoom** [comment]
Good eye @Nancy-Salpepi. There was an extra touchArea being added for the radio button group.  I've removed it in the above commit, see screenshot below.  I'll go ahead and close this issue.

<img width="253" alt="screenshot_3397" src="https://github.com/phetsims/hookes-law/assets/3046552/22e593b6-a449-44c1-8eec-9e3027cff53d">
