### ISSUE TITLE
Additional decimal in applied force number display

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/hookes-law#90]
From https://github.com/phetsims/qa/issues/1102, I noticed there is an extra decimal point on this number control compared to published. Making an issue in case it is not intentional:

![image](https://private-user-images.githubusercontent.com/6396244/343969837-1b6f9739-cf0c-4fde-b1dc-9a12360d362f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODU5OTEsIm5iZiI6MTcxOTc4NTY5MSwicGF0aCI6Ii82Mzk2MjQ0LzM0Mzk2OTgzNy0xYjZmOTczOS1jZjBjLTRmZGUtYjFkYy05YTEyMzYwZDM2MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMjIxNDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDAzYzk2NDVjNDJhMmQ0Yzg3OGFhMjQ1MjA3MzJjOGI0NThiYmQ0MTFhNDQ4Nzc4NThkZTgxMDdhY2Q2YTBjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GxfVXt7hCYLgLnzySlPG6FLQcOj5bGl4eaTYV5ms2lM)

**Comment by pixelzoom** [comment]
I don't see a screenshot in @jessegreenberg's report above, just a '?' where the screenshot should be.  But comparing the production version 1.0.38 to main, I see that production has no decimal places, and main has 1 decimal place.

**Comment by arouinfar** [comment]
Here's the screenshot originally posted in https://github.com/phetsims/qa/issues/1102

<img width="354" alt="image" src="https://github.com/phetsims/hookes-law/assets/8419308/3afbffcf-d455-476f-a437-2b46a858d2a7">


This was an intentional change made in #57, see https://github.com/phetsims/hookes-law/issues/57#issuecomment-840101765 for full details. Closing.
