### ISSUE TITLE
Update credits for 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#93]
Fro https://github.com/phetsims/hookes-law/issues/91

**Comment by pixelzoom** [comment]
From dev test https://github.com/phetsims/qa/issues/1102#issuecomment-2200769174:

> QA credits: Jaron Droder, Matthew Moore, Nancy Salpepi, Kathryn Woessner

**Comment by pixelzoom** [comment]
Please specify any additional QA credits for https://github.com/phetsims/qa/issues/1104.

**Comment by Nancy-Salpepi** [comment]
No additional changes for https://github.com/phetsims/qa/issues/1104

**Comment by pixelzoom** [comment]
Please specify any additional QA credits for https://github.com/phetsims/qa/issues/1112.

**Comment by KatieWoe** [comment]
No new additions

**Comment by pixelzoom** [comment]
RC testing is done, and we are ready to publish 1.1.  Closing.
