### ISSUE TITLE
Layout changes on Energy screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#95]
For https://github.com/phetsims/qa/issues/1102 ... From https://github.com/phetsims/hookes-law/issues/81#issuecomment-2197533334 by @Nancy-Salpepi:

A couple of differences I see when comparing to the published version:
-  On the Energy screen, the Energy Checkbox has shifted to the right 
- On the Energy screen, when at max values the Applied Force arrow now touches the panel. 

Dev Version vs. Published:

<img width="359" alt="Screenshot 2024-06-28 at 8 30 10 AM" src="https://github.com/phetsims/qa/assets/87318828/6d07670f-2fbb-4f2f-8be7-3d49426dd64f"> <img width="359" alt="Screenshot 2024-06-28 at 8 29 58 AM" src="https://github.com/phetsims/qa/assets/87318828/eee656ba-788b-4a92-bf88-2e70e9f09ae4">

 Also with ?stringTest=dynamic, the text background of the Applied Force Value can overlap the panel slightly when Displacement =1.
<img width="259" alt="Screenshot 2024-06-28 at 12 06 40 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/7cba801b-e15d-497d-bf46-1590ce61dce7">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please review, close if OK.  Note the decision NOT to right-align icons in https://github.com/phetsims/hookes-law/issues/100.

**Comment by Nancy-Salpepi** [comment]
These issues look fixed on main:
- [x] On the Energy screen, the Energy Checkbox has shifted to the right
- [x] On the Energy screen, when at max values the Applied Force arrow now touches the panel
- [x] Also with ?stringTest=dynamic, the text background of the Applied Force Value can overlap the panel slightly when Displacement =1.

On the Systems Screen, I noticed that with longer strings the text background for the Applied Force can overlap the purple Spring Force arrow. I also see this in published with ?stringTest=double.....so feel free to ignore and close. 

<img width="290" alt="Screenshot 2024-07-02 at 3 09 25 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/4109c799-04cb-436e-a73d-d5372ea32ff0">

**Comment by pixelzoom** [comment]
The problem in https://github.com/phetsims/hookes-law/issues/95#issuecomment-2204130191 is that there's a translucent background behind each vector value.  The margins of that value were a function of the dimensions of the value, so as the value got longer, the margins got bigger, and hence the overlap.  Constant margins make more sense, implemented in https://github.com/phetsims/hookes-law/commit/3918aa935d6f28e5f321201624299e1e198dc8ee.

 Back to @Nancy-Salpepi for another verification, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks nice. 
Closing.
