### ISSUE TITLE
Bottom panel sizes are slightly different heights in locales other than English.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#96]
For https://github.com/phetsims/qa/issues/1102 ... In https://github.com/phetsims/hookes-law/issues/81#issuecomment-2197533334 by @Nancy-Salpepi:

For https://github.com/phetsims/qa/issues/1102 in locales other than English, the bottom panel sizes are slightly different heights.
Here are the Spring and Applied Force panels for the screens 1&2 in Hebrew:
<img width="527" alt="Screenshot 2024-06-28 at 3 36 30 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/476c0825-44d7-4264-b416-924bd20d1ea8">
<img width="896" alt="Screenshot 2024-06-28 at 3 39 59 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/a418a80a-9760-432f-a8ad-62001145980e">
And here are the Spring and Displacement panels for screen 3 in Hebrew:
<img width="649" alt="Screenshot 2024-06-28 at 3 48 27 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/519b20d7-055c-4b67-b845-38f9b6826a9c">

**Comment by pixelzoom** [comment]
Hebrew is `locale=iw`, or make this selection in Preferences:

<img width="1052" alt="screenshot_3388" src="https://github.com/phetsims/hookes-law/assets/3046552/15c5eea1-8c2c-4900-acf9-e7786f11b7b6">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please verify, close if OK.

**Comment by Nancy-Salpepi** [comment]
Tested with several locales and with ?stringTest=dynamic. All looks good on main. Closing.
