### ISSUE TITLE
"Equilibrium Position" label is scaled down.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#97]
For https://github.com/phetsims/qa/issues/1102 ... From https://github.com/phetsims/hookes-law/issues/81#issuecomment-2198782920 by @jessegreenberg:

A couple of notes from https://github.com/phetsims/qa/issues/1102 regarding layout changes, possibly from dynamic locale:

The layout has changed and now this text has scaled down: 
     <img width="214" alt="image" src="https://github.com/phetsims/hookes-law/assets/8419308/83cbd360-aafd-43d0-8e9d-ed016654152a">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi would you mind verifying this? Close if OK please.

**Comment by Nancy-Salpepi** [comment]
"Equilibrium Position' is now larger on all screens. 
In general, the font size for a lot of the text in this panel is smaller than in published. Is that OK?
<img width="635" alt="Screenshot 2024-07-01 at 5 21 35 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/74bf2528-a650-4027-9d42-06162146d5cc">
<img width="680" alt="Screenshot 2024-07-01 at 5 20 57 PM" src="https://github.com/phetsims/hookes-law/assets/87318828/809842d8-b929-4762-9138-a39065c9b32d">

**Comment by pixelzoom** [comment]
Font sizes should now be true to the 1.0 version.  @Nancy-Salpepi please review, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks great! Closing.
