### ISSUE TITLE
Unwanted icon to the right of "Spring Forces" checkbox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/hookes-law#99]
For https://github.com/phetsims/qa/issues/1102 ...

In 1.0, the Spring Force checkbox has no icon to the right of it:
 
<img width="274" alt="screenshot_3390" src="https://github.com/phetsims/hookes-law/assets/3046552/e67be50a-61e2-4b05-ba9b-e986d6399c4d">

In main, the Spring Force checkbox now has an icon (blue vector) to the right of it:

<img width="277" alt="screenshot_3389" src="https://github.com/phetsims/hookes-law/assets/3046552/2a597d91-2626-47d4-987e-c886f75b3d00">

This seems like a regression, since the purpose of the radio buttons below the Spring Force checkbox is to select the representation of spring force. 

@arouinfar To you recall any intentional change related to this, or do you also think this is a regression?

**Comment by arouinfar** [comment]
@pixelzoom this looks like a regression to me. There shouldn't be an icon next to the Spring Force checkbox when it has nested radio buttons.

**Comment by pixelzoom** [comment]
Thanks @arouinfar. Icon has been removed. Closing.
